### ISSUE TITLE
Enhance test architecture

### ISSUE THREAD

**Issue by JocelynDelalande** [oasiswork/zimsoap#11]
I'm thinking about reworking test architecture.

# Current test architecture

- Local tests only
- some unit tests for what is testable that way
- Vagrant Zimbra VM
- [integration tests](http://stackoverflow.com/a/4904533/1377500) backing on that vagrant VM.

# Caveats

- Zimbra vagrant VM is really really long to boot or resume and can make virtualizing host unresponsive for minutes
- No continuous integration, the VM has to be booted and tests ran even for trivial modifications
- No continuous integration, cannot be sure contributions have been tested without running them locally
- Hard to run integration tests for developpers using windows

# Proposal

## Part 1

- Leaving vagrant vm as the default option
- Make the host on which the integration tests are run configurable (defaulting but not forcing to the vagrant vm), as @dploeger does on https://github.com/Zimbra-Community/python-zimbra

## Part 2

- Travis continuous integration, backing on a test zimbra server (host details and credentials being not public, but part of travis settings)

@manens : I would be happy to hear what you think about that proposal, would it ease the process of writting/running tests for you ?

**Comment by manens** [comment]
Hi JocelynDelalande,

having the test host as a configurable settings is a good option, it will be easier for me.

Do you plan to do a global setUp to create all accounts needed for tests ? or we will have to create accounts/domain/... by hand ?

Best regards,

**Comment by JocelynDelalande** [comment]
> Do you plan to do a global setUp to create all accounts needed for tests ? or we will have to create 
> accounts/domain/... by hand ?

@manens I will provide a script and/or ansible playbook to provision the required accounts/domains.

**Comment by JocelynDelalande** [comment]
I think I reached the Part1 of my proposal.
Everything is supposed to be documented clearly in the README.md
@manens  I would be happy to have your feedback on testing before I merge.

**Comment by JocelynDelalande** [comment]
@manens  no news from you, merged in b0878464bc41db3ce6a61db349c2352a8b7ef374
